/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gmp.comps.datefield;

import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 *
 * @author kaciano
 */
public class GMPDateField extends JPanel {

    /**
     * Creates new form GMPDateField
     */
    public GMPDateField() {
        initComponents();
        jPopDate.add(jPCalendar);
        //jCBYear.setModel(new DefaultComboBoxModel(getYearList()));
    }

    public int[] getYearList() {
        int actualYear = new Date().getYear();
        int firstYear = actualYear - 100;
        int[] yearList = new int[firstYear];
        int j = 0;
        for (int i = actualYear; i > firstYear; i--) {
            yearList[j] = i;
            j++;
            if (j == (actualYear - firstYear)) {
                break;
            }
        }
        return yearList;
    }

    /**
     *
     * @return
     */
    public int getMonth() {
        return jXCalendar.getCalendar().getTime().getMonth();
    }

    /**
     *
     * @return
     */
    public int getYear() {
        return jXCalendar.getCalendar().getTime().getYear();
    }

    /**
     *
     * @param month
     */
    public void setMonth(int month) {
        Date date = jXCalendar.getCalendar().getTime();
        date.setMonth(month);
        jXCalendar.getCalendar().setTime(date);
        jXCalendar.repaint();
        jXCalendar.revalidate();
    }

    /**
     *
     * @param month
     * @param year
     */
    public void setMonth(int month, int year) {
        Date date = jXCalendar.getCalendar().getTime();
        date.setMonth(month);
        date.setYear(year);
        jXCalendar.getCalendar().setTime(date);
        jXCalendar.repaint();
        jXCalendar.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopDate = new javax.swing.JPopupMenu();
        jPCalendar = new javax.swing.JPanel();
        jTBPrev = new javax.swing.JToolBar();
        jBPreviousMonth = new javax.swing.JButton();
        jTBYear = new javax.swing.JToolBar();
        jCBYear = new javax.swing.JComboBox();
        jTBNext = new javax.swing.JToolBar();
        jBNextMonth = new javax.swing.JButton();
        jXCalendar = new org.jdesktop.swingx.JXMonthView();
        jFTDate = new javax.swing.JFormattedTextField();
        jBDatePick = new javax.swing.JButton();

        jTBPrev.setFloatable(false);
        jTBPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jBPreviousMonth.setIcon(new javax.swing.ImageIcon("/home/kaciano/NetBeansProjects/GMP-EE/GMP-EE-desktop/GMPComps/src/main/resources/res/datefield/16/circle_skip_previous.png")); // NOI18N
        jBPreviousMonth.setFocusable(false);
        jBPreviousMonth.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPreviousMonth.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBPreviousMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPreviousMonthActionPerformed(evt);
            }
        });
        jTBPrev.add(jBPreviousMonth);

        jTBYear.setFloatable(false);
        jTBYear.add(jCBYear);

        jTBNext.setFloatable(false);

        jBNextMonth.setIcon(new javax.swing.ImageIcon("/home/kaciano/NetBeansProjects/GMP-EE/GMP-EE-desktop/GMPComps/src/main/resources/res/datefield/16/circle_skip_next.png")); // NOI18N
        jBNextMonth.setFocusable(false);
        jBNextMonth.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNextMonth.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jTBNext.add(jBNextMonth);

        javax.swing.GroupLayout jPCalendarLayout = new javax.swing.GroupLayout(jPCalendar);
        jPCalendar.setLayout(jPCalendarLayout);
        jPCalendarLayout.setHorizontalGroup(
            jPCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCalendarLayout.createSequentialGroup()
                .addComponent(jTBPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTBYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jTBNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jXCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );
        jPCalendarLayout.setVerticalGroup(
            jPCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCalendarLayout.createSequentialGroup()
                .addGroup(jPCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTBNext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTBYear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPCalendarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTBNext, jTBPrev, jTBYear});

        jFTDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jFTDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jBDatePick.setIcon(new javax.swing.ImageIcon("/home/kaciano/NetBeansProjects/GMP-EE/GMP-EE-desktop/GMPComps/src/main/resources/res/datefield/16/calendar.png")); // NOI18N
        jBDatePick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDatePickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFTDate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBDatePick))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jFTDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBDatePick, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBDatePickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDatePickActionPerformed
        jBDatePick.setComponentPopupMenu(jPopDate);
        jBDatePick.getComponentPopupMenu().show();
        jBDatePick.setComponentPopupMenu(null);
    }//GEN-LAST:event_jBDatePickActionPerformed

    private void jBPreviousMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPreviousMonthActionPerformed
        int month = getMonth();
        if (month == 1) {
            month = 12;
            setMonth(month, getYear() - 1);
        } else {
            setMonth(month - 1);
        }
    }//GEN-LAST:event_jBPreviousMonthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDatePick;
    private javax.swing.JButton jBNextMonth;
    private javax.swing.JButton jBPreviousMonth;
    private javax.swing.JComboBox jCBYear;
    private javax.swing.JFormattedTextField jFTDate;
    private javax.swing.JPanel jPCalendar;
    private javax.swing.JPopupMenu jPopDate;
    private javax.swing.JToolBar jTBNext;
    private javax.swing.JToolBar jTBPrev;
    private javax.swing.JToolBar jTBYear;
    private org.jdesktop.swingx.JXMonthView jXCalendar;
    // End of variables declaration//GEN-END:variables
}
