package comps.wizard;

import comps.wizard.task.WizardTask;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author kaciano
 */
public class WizardPanel extends JPanel {

    private List<WizardTask> taskList;

    /**
     * Creates new form WizardPanel
     */
    public WizardPanel() {
        this.taskList = new LinkedList<>();
        initComponents();
    }

    /**
     * Adiciona nova WizardTask à lista
     *
     * @param task WizardTask
     */
    public void addTask(WizardTask task) {
        this.taskList.add(task);
    }

    /**
     * Remove a WizardTask da lista
     *
     * @param task WizardTask
     */
    public void removeTask(WizardTask task) {
        if (this.taskList.contains(task)) {
            this.taskList.remove(task);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCommand = new javax.swing.JPanel();
        jBPrevious = new javax.swing.JButton();
        jBNext = new javax.swing.JButton();
        jPContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wizardTaskList1 = new comps.wizard.task.list.WizardTaskList();

        jPCommand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jBPrevious.setText("Anterior");
        jPCommand.add(jBPrevious);

        jBNext.setText("Próximo");
        jPCommand.add(jBNext);

        jPContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jScrollPane1.setViewportView(wizardTaskList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPCommand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold desc="Get's & Set's" defaultstate="collapsed">
    public List<WizardTask> getTaskList() {
        return taskList;
    }

    public void setTaskList(List<WizardTask> taskList) {
        this.taskList = taskList;
    }

    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBNext;
    private javax.swing.JButton jBPrevious;
    private javax.swing.JPanel jPCommand;
    private javax.swing.JPanel jPContent;
    private javax.swing.JScrollPane jScrollPane1;
    private comps.wizard.task.list.WizardTaskList wizardTaskList1;
    // End of variables declaration//GEN-END:variables
}
