package comps.wizard;

import comps.wizard.event.WizardEvent;
import comps.wizard.task.WizardTask;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JPanel;

/**
 * Painel de gerenciamento para fluxo de processos
 *
 * @author kaciano
 * @version 1.0
 * @since 1.0
 */
public class WizardPanel extends JPanel {

    private WizardEvent event;
    private List<WizardTask> taskList;

    /**
     * Cria nova instancia de WizardPanel
     */
    public WizardPanel() {
        this.event = null;
        this.taskList = new LinkedList<>();
        initComponents();
        initialize();
    }

    /**
     * Cria nova instancia de WizardPanel
     *
     * @param event WizardEvent
     */
    public WizardPanel(WizardEvent event) {
        this.event = event;
        this.taskList = event.getTaskList();
        initComponents();
        initialize();
    }

    /**
     * Cria nova instancia de WizardPanel
     *
     * @param event WizardEvent
     * @param taskList Lista de tarefas
     */
    public WizardPanel(WizardEvent event, List<WizardTask> taskList) {
        this.event = event;
        this.taskList = taskList;
        initComponents();
        initialize();
    }

    /**
     * Inicializa os dados
     */
    private void initialize() {
        this.wizardTaskList.setTaskList(taskList);
        if (!taskList.isEmpty()) {
            setHeader(taskList.get(0));
        } else {
            System.out.println("TaskList empty!");
        }
    }

    /**
     * Adiciona nova WizardTask à lista
     *
     * @param task WizardTask
     */
    public void addTask(WizardTask task) {
        this.taskList.add(task);
        setHeader(taskList.get(0));
    }

    /**
     * Remove a WizardTask da lista
     *
     * @param task WizardTask
     */
    public void removeTask(WizardTask task) {
        if (this.taskList.contains(task)) {
            this.taskList.remove(task);
        }
    }

    /**
     * Modifica o painel da tarefa atual
     *
     * @param panel JPanel
     */
    public void setTaskPanel(JPanel panel) {
        this.jPContent.removeAll();
        this.jPContent.add(panel);
    }

    /**
     * Modifica os dados do cabeçalho
     *
     * @param title Titulo do cabeçalho
     * @param description Descrição do cabeçalho
     */
    public void setHeader(String title, String description) {
        this.jLTaskTitle.setText(title);
        this.jLTaskDescription.setText(description);
    }

    /**
     * Modifica os dados do cabeçalho
     *
     * @param task WizardTask
     */
    public void setHeader(WizardTask task) {
        this.jLTaskTitle.setText(task.getTitle());
        this.jLTaskDescription.setText(task.getDescription());
    }

    /**
     * Carrega a lista de tarefas
     *
     * @param tasklist Lista de tarefas
     */
    public void loadTaskList(List<WizardTask> tasklist) {
        this.wizardTaskList.setTaskList(taskList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCommand = new javax.swing.JPanel();
        gBPrevious = new comps.button.GMPButton();
        gBNext = new comps.button.GMPButton();
        gBCancel = new comps.button.GMPButton();
        gBInfo = new comps.button.GMPButton();
        jPContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wizardTaskList = new comps.wizard.task.list.WizardTaskList();
        jPHeader = new javax.swing.JPanel();
        jLTaskTitle = new javax.swing.JLabel();
        jLTaskDescription = new javax.swing.JLabel();

        jPCommand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        gBPrevious.setText("Anterior");
        gBPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBPreviousActionPerformed(evt);
            }
        });
        jPCommand.add(gBPrevious);

        gBNext.setText("Próximo");
        gBNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBNextActionPerformed(evt);
            }
        });
        jPCommand.add(gBNext);

        gBCancel.setText("Cancelar");
        gBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBCancelActionPerformed(evt);
            }
        });
        jPCommand.add(gBCancel);

        gBInfo.setText("Informações");
        gBInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBInfoActionPerformed(evt);
            }
        });
        jPCommand.add(gBInfo);

        jPContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPContent.setLayout(new java.awt.GridLayout(1, 1));

        jScrollPane1.setViewportView(wizardTaskList);

        jPHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLTaskTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLTaskTitle.setText("Titulo");

        jLTaskDescription.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLTaskDescription.setText("Descrição");

        javax.swing.GroupLayout jPHeaderLayout = new javax.swing.GroupLayout(jPHeader);
        jPHeader.setLayout(jPHeaderLayout);
        jPHeaderLayout.setHorizontalGroup(
            jPHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTaskTitle)
                    .addComponent(jLTaskDescription))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPHeaderLayout.setVerticalGroup(
            jPHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTaskTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTaskDescription)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPCommand, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gBPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBPreviousActionPerformed
        event.previous();
    }//GEN-LAST:event_gBPreviousActionPerformed

    private void gBNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBNextActionPerformed
        event.next();
    }//GEN-LAST:event_gBNextActionPerformed

    private void gBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBCancelActionPerformed
        event.cancel();
    }//GEN-LAST:event_gBCancelActionPerformed

    private void gBInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBInfoActionPerformed
        event.info();
    }//GEN-LAST:event_gBInfoActionPerformed

    //<editor-fold desc="Get's & Set's" defaultstate="collapsed">
    public List<WizardTask> getTaskList() {
        return taskList;
    }

    public void setTaskList(List<WizardTask> taskList) {
        this.taskList = taskList;
        if (!taskList.isEmpty()) {
            setHeader(taskList.get(0));
        } else {
            System.out.println("TaskList empty!");
        }
    }

    public WizardEvent getEvent() {
        return event;
    }

    public void setEvent(WizardEvent event) {
        this.event = event;
    }

    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private comps.button.GMPButton gBCancel;
    private comps.button.GMPButton gBInfo;
    private comps.button.GMPButton gBNext;
    private comps.button.GMPButton gBPrevious;
    private javax.swing.JLabel jLTaskDescription;
    private javax.swing.JLabel jLTaskTitle;
    private javax.swing.JPanel jPCommand;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private comps.wizard.task.list.WizardTaskList wizardTaskList;
    // End of variables declaration//GEN-END:variables
}
