package br.com.gmp.comps.textfield;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author kaciano
 */
public class NumericTextField extends JTextField {

    private int limit = 0;

    public NumericTextField() {
        initComponents();
        addListeners();
    }

    public NumericTextField(int limit) {
        initComponents();
        this.limit = limit;
        addListeners();
    }

    private void addListeners() {
        addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String s = getText();
                if (s.length() > 0) {
                    for (int i = 0; i < s.length(); i++) {
                        if (Character.isLetter(s.charAt(i))) {
                            JOptionPane.showMessageDialog(null, "Somente números",
                                    "Informação", JOptionPane.INFORMATION_MESSAGE);
                            String sub = getText().substring(0, getText().length() - 1);
                            setText(sub);
                            grabFocus();
                            break;
                        }
                    }
                }
                if (limit != 0 && getText().length() > limit) {
                    String sub = getText().substring(0, getText().length() - 1);
                    setText(sub);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        setPreferredSize(new java.awt.Dimension(100, 25));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
