package comps.menuitem;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Action;
import javax.swing.Icon;
import javax.swing.JMenuItem;
import javax.swing.border.LineBorder;

/**
 * Item de menu com formatação própria
 *
 * @author kaciano
 */
public class GMPMenuItem extends JMenuItem {

    private String prefix;
    private String title;

    /**
     * Cria nova instancia de GMPMenuItem
     *
     * @param prefix Prefixo
     * @param title Titulo
     */
    public GMPMenuItem(String prefix, String title) {
        initComponents();
        setTitle(prefix, title);
    }

    /**
     * Cria nova instancia de GMPMenuItem
     *
     * @param prefix Prefixo
     * @param title Titulo
     * @param a Action
     */
    public GMPMenuItem(String prefix, String title, Action a) {
        super(a);
        this.prefix = prefix;
        this.title = title;
        setTitle(prefix, title);
    }

    /**
     * Cria nova instancia de GMPMenuItem
     *
     * @param prefix Prefixo
     * @param title Titulo
     * @param icon Icone
     */
    public GMPMenuItem(String prefix, String title, Icon icon) {
        super(icon);
        this.prefix = prefix;
        this.title = title;
        setTitle(prefix, title);
    }

    /**
     * Adiciona o titulo com a formatação correta
     *
     * @param prefix Prefixo
     * @param title Titulo
     */
    private void setTitle(String prefix, String title) {
        super.setText("<html><b>" + prefix + "</b> " + title + "</html>");
    }

    /**
     * Adiciona os listeners especificos
     */
    private void addListeners() {
        this.setBorder(new LineBorder(Color.gray));

        this.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent e) {
                super.mouseEntered(e);
                setBackground(Color.orange);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                super.mouseExited(e);
                setBackground(new JMenuItem().getBackground());
            }

            @Override
            public void mousePressed(MouseEvent e) {
                super.mousePressed(e);
                setBackground(Color.red.darker());
            }

//            @Override
//            public void mouseReleased(MouseEvent e) {
//                super.mouseReleased(e);
//                setBackground(new JMenuItem().getBackground());
//            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Retorna o prefixo
     *
     * @return Prefixo
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Modifica o prefixo
     *
     * @param prefix Novo Prefixo
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
        setTitle(prefix, title);
    }

    /**
     * Retorna o titulo
     *
     * @return Titulo
     */
    public String getTitle() {
        return title;
    }

    /**
     * Modifica o titulo
     *
     * @param title Novo titulo
     */
    public void setTitle(String title) {
        this.title = title;
        setTitle(prefix, title);
    }
}
