package br.com.gmp.comps.keyboard;

import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author kaciano
 */
public class GMPKeyBoard extends JPanel {

    private JTextField textField;

    /**
     * Creates new form GMPKeyBoard
     */
    public GMPKeyBoard() {
        initialize();
    }

    /**
     * 
     * @param textField 
     */
    public GMPKeyBoard(JTextField textField) {
        this.textField = textField;
        initialize();
    }

    private void initialize() {
        initComponents();
    }

    public JTextField getTextField() {
        return textField;
    }

    public void setTextField(JTextField textField) {
        this.textField = textField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPKeys = new javax.swing.JPanel();
        jBA = new javax.swing.JButton();
        jBB = new javax.swing.JButton();
        jBC = new javax.swing.JButton();
        jBD = new javax.swing.JButton();
        jBE = new javax.swing.JButton();
        jBF = new javax.swing.JButton();
        jBG = new javax.swing.JButton();
        jBH = new javax.swing.JButton();
        jBI = new javax.swing.JButton();
        jBJ = new javax.swing.JButton();
        jBK = new javax.swing.JButton();
        jBL = new javax.swing.JButton();
        jBM = new javax.swing.JButton();
        jBN = new javax.swing.JButton();
        jBO = new javax.swing.JButton();
        jBP = new javax.swing.JButton();
        jBQ = new javax.swing.JButton();
        jBR = new javax.swing.JButton();
        jBS = new javax.swing.JButton();
        jBT = new javax.swing.JButton();
        jBU = new javax.swing.JButton();
        jBV = new javax.swing.JButton();
        jBX = new javax.swing.JButton();
        jBW = new javax.swing.JButton();
        jBY = new javax.swing.JButton();
        jBZ = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jPControls = new javax.swing.JPanel();
        jBBackSpace = new javax.swing.JButton();
        jBSpace = new javax.swing.JButton();
        jBEnter = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        jBA.setText("A");
        jPKeys.add(jBA);

        jBB.setText("B");
        jPKeys.add(jBB);

        jBC.setText("C");
        jBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBC);

        jBD.setText("D");
        jBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBD);

        jBE.setText("E");
        jBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBE);

        jBF.setText("F");
        jBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBF);

        jBG.setText("G");
        jBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBG);

        jBH.setText("H");
        jBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBH);

        jBI.setText("I");
        jBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBI);

        jBJ.setText("J");
        jBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBJ);

        jBK.setText("K");
        jBK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBK);

        jBL.setText("L");
        jBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBL);

        jBM.setText("M");
        jBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBM);

        jBN.setText("N");
        jBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBN);

        jBO.setText("O");
        jBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBO);

        jBP.setText("P");
        jBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBP);

        jBQ.setText("Q");
        jBQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBQ);

        jBR.setText("R");
        jBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBR);

        jBS.setText("S");
        jBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBS);

        jBT.setText("T");
        jBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBT);

        jBU.setText("U");
        jBU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBU);

        jBV.setText("V");
        jBV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBV);

        jBX.setText("X");
        jBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBX);

        jBW.setText("W");
        jBW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBW);

        jBY.setText("Y");
        jBY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBY);

        jBZ.setText("Z");
        jBZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBZ);

        jB0.setText("0");
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB0);

        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB1);

        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB2);

        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB3);

        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB4);

        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB5);

        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB6);

        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB7);

        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB8);

        jB9.setText("9");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB9);

        jBBackSpace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/direction/upLeft.png"))); // NOI18N
        jBBackSpace.setText("Backspace");
        jBBackSpace.setToolTipText("Backspace");
        jBBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackSpaceActionPerformed(evt);
            }
        });
        jPControls.add(jBBackSpace);

        jBSpace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/focus/focus.png"))); // NOI18N
        jBSpace.setText("Space");
        jBSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSpaceActionPerformed(evt);
            }
        });
        jPControls.add(jBSpace);

        jBEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/direction/rightCenter.png"))); // NOI18N
        jBEnter.setText("Enter");
        jBEnter.setToolTipText("Enter");
        jBEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnterActionPerformed(evt);
            }
        });
        jPControls.add(jBEnter);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/label/label.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPControls.add(jToggleButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPControls, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
            .addComponent(jPKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPControls, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jBEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEnterActionPerformed

    private void jBSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSpaceActionPerformed

    private void jBBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackSpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBackSpaceActionPerformed

    private void jBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBA;
    private javax.swing.JButton jBB;
    private javax.swing.JButton jBBackSpace;
    private javax.swing.JButton jBC;
    private javax.swing.JButton jBD;
    private javax.swing.JButton jBE;
    private javax.swing.JButton jBEnter;
    private javax.swing.JButton jBF;
    private javax.swing.JButton jBG;
    private javax.swing.JButton jBH;
    private javax.swing.JButton jBI;
    private javax.swing.JButton jBJ;
    private javax.swing.JButton jBK;
    private javax.swing.JButton jBL;
    private javax.swing.JButton jBM;
    private javax.swing.JButton jBN;
    private javax.swing.JButton jBO;
    private javax.swing.JButton jBP;
    private javax.swing.JButton jBQ;
    private javax.swing.JButton jBR;
    private javax.swing.JButton jBS;
    private javax.swing.JButton jBSpace;
    private javax.swing.JButton jBT;
    private javax.swing.JButton jBU;
    private javax.swing.JButton jBV;
    private javax.swing.JButton jBW;
    private javax.swing.JButton jBX;
    private javax.swing.JButton jBY;
    private javax.swing.JButton jBZ;
    private javax.swing.JPanel jPControls;
    private javax.swing.JPanel jPKeys;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
